name: Generate ASCII

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 

      - name: List repo files
        run: ls -lrtha  

      - name: Executing shell script to install cowsay program
        run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh
        

      
          
